services:
  app:
    image: chronoscope
    build: .
    container_name: app
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - export FLASK_APP=chronoscope
